# Generated by Django 5.1.4 on 2025-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hallticket_NO', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('TELUGU', models.IntegerField()),
                ('HINDI', models.IntegerField()),
                ('ENGLISH', models.IntegerField()),
                ('MATHS', models.IntegerField()),
                ('SCIENCE', models.IntegerField()),
                ('SOCIAL', models.IntegerField()),
            ],
        ),
    ]
